name = "hn"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-06"
main = "dist/worker.js"

[site]
bucket = "./dist"
entry-point = ""
include = ["assets/**"]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"